name: Test Version Update Action

on:
  push: {}

jobs:
  prereqs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.17.0"
      - name: Install Dependencies
        run: |
          apt update
          apt install -y jq
      - name: Run Tests
        run: |
          task test
